<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCX7soBf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCX7soBf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCX7soBf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCX7soBf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCX7soBf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CX7soBf',
    'container.build_id' => '92608b84',
    'container.build_time' => 1565090078,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCX7soBf');
