<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'partenaire' => [[], ['_controller' => 'App\\Controller\\PartenaireController::index'], [], [['text', '/api/partenaire']], [], []],
    'compt' => [[], ['_controller' => 'App\\Controller\\PartenaireController::ajoutcompt'], [], [['text', '/api/ajoutcompt']], [], []],
    'depot' => [[], ['_controller' => 'App\\Controller\\PartenaireController::depot'], [], [['text', '/api/depot']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/api/register']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/api/login']], [], []],
    'ajoutpart' => [[], ['_controller' => 'App\\Controller\\SecurityController::ajoutpart'], [], [['text', '/api/ajoutpart']], [], []],
    'ajoutpartuser' => [[], ['_controller' => 'App\\Controller\\SecurityController::ajoutpartuser'], [], [['text', '/api/ajoutpartuser']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
